### PR TITLE
Changes of the calendar

### PR DESCRIPTION
**Pull request by GauthLin**
Here are the changes:
- New widget which lists future events
- A lot of bugs fixes
- Add security to the workspace's agenda
- Add tasks and the possibility to mark them as done or not done
- Upgrade the fullcalendar plugin to version 2.3.1.
- Change some translation's keys

### CODE REVIEW

**Comment by ngodfraind** [comment]
Permissions were changed. Is it normal ?

**Comment by GauthLin** [comment]
I don't know why it has changed but now permissions are set as before.

**Comment by ngodfraind** [comment]
You also should put the calendar in the FrontEndBundle. This is where we put librairies we can't handle with composer. Remove the old one and use your version instead.

**Comment by GauthLin** [comment]
I put the plugin calendar in the AgendaBundle because it's the only one that uses this plugin.
So that there is no dependence with other bundles or incompatibility if the users still use the old version of AgendaBundle that use FullCalendar 2.2.1. and not 2.3.1.

For me, it's the best solution but if you prefer I can move the files and put them into the FrontEndBundle ?

**Comment by ngodfraind** [comment]
True.
Can you remove it from the FrontEndBundle in order to make everything clean
?

2015-05-12 15:07 GMT+02:00 Gauthier Linard notifications@github.com:

> I put the plugin calendar in the AgendaBundle because it's the only one
> that uses this plugin.
> So that there is no dependence with other bundles or incompatibility if
> the users still use the old version of AgendaBundle that use FullCalendar
> 2.2.1. and not 2.3.1.
> 
> For me, it's the best solution but if you want I can move the files and
> put them into the FrontEndBundle ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/claroline/AgendaBundle/pull/4#issuecomment-101268823.

## 

Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by GauthLin** [comment]
Ok

**Comment by GauthLin** [comment]
There are more changes that arrive so don't tag yet please.

**Pull request merged**
